stages:
  data_load:
    cmd: python src/stages/data_load.py
  featurize:
    cmd: python src/stages/featurize.py
  data_split:
    cmd: python src/stages/data_split.py
  train:
    cmd: python src/stages/train.py

  evaluate:
    cmd: python src/stages/evaluate.py
    deps:
    - data/processed/features.csv
    - models/model.pkl
    - src/stages/evaluate.py
    outs:
    - eval/importance.png
    - eval/live/plots:
        cache: false
    - eval/prc:
        cache: false
    metrics:
    - eval/live/metrics.json:
        cache: false
