stages:
  data_load:
    cmd: python src/stages/data_load.py
  featurize:
    cmd: python src/stages/featurize.py
  data_split:
    cmd: python src/stages/data_split.py
  train:
    cmd: python src/stages/train.py
    outs: models/model.joblib
  evaluate:
    cmd: python src/stages/evaluate.py
