base:
  random_state: 42

data_load:
  dataset_csv: 'C:/Users/Ayo Agbaje/Desktop/ML-Pipelines/data/raw/car_price_prediction.csv'


featurize:
  features_path: 'C:/Users/Ayo Agbaje/Desktop/ML-Pipelines/data/processed/features.csv'
  target_column: 'PRICE'


data_split:
  trainset_path: 'C:/Users/Ayo Agbaje/Desktop/ML-Pipelines/data/processed//train_features.csv'
  testset_path: 'C:/Users/Ayo Agbaje/Desktop/ML-Pipelines/data/processed//test_features.csv'

train:
  n_estimators: 100
  n_jobs: 1
  max_leaf_nodes: 2
  model_path: 'C:/Users/Ayo Agbaje/Desktop/ML-Pipelines/models/model.joblib'


evaluate:
  reports_dir: '../reports/figures/'
  scatterplot: 'scatterplot.jpg'
